import { COLORS_WITHOUT_KINDS } from 'utils/constants';
export const buttonColorVariants = {
  purple1: {
    backgroundColor: '$purple1',
    border: '1px solid $purple12',
    color: '$purple12',
    '&:active, &:focus-visible': { outlineColor: '$purple12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple12',
      transition: 'all 0.3s ease',
    },
  },
  purple2: {
    backgroundColor: '$purple2',
    border: '1px solid $purple12',
    color: '$purple12',
    '&:active, &:focus-visible': { outlineColor: '$purple12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple12',
      transition: 'all 0.3s ease',
    },
  },
  purple3: {
    backgroundColor: '$purple3',
    border: '1px solid $purple12',
    color: '$purple12',
    '&:active, &:focus-visible': { outlineColor: '$purple12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple12',
      transition: 'all 0.3s ease',
    },
  },
  purple4: {
    backgroundColor: '$purple4',
    border: '1px solid $purple12',
    color: '$purple12',
    '&:active, &:focus-visible': { outlineColor: '$purple12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple12',
      transition: 'all 0.3s ease',
    },
  },
  purple5: {
    backgroundColor: '$purple5',
    border: '1px solid $purple11',
    color: '$purple11',
    '&:active, &:focus-visible': { outlineColor: '$purple11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple11',
      transition: 'all 0.3s ease',
    },
  },
  purple6: {
    backgroundColor: '$purple6',
    border: '1px solid $purple11',
    color: '$purple11',
    '&:active, &:focus-visible': { outlineColor: '$purple11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple11',
      transition: 'all 0.3s ease',
    },
  },
  purple7: {
    backgroundColor: '$purple7',
    border: '1px solid $purple12',
    color: '$purple12',
    '&:active, &:focus-visible': { outlineColor: '$purple12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple12',
      transition: 'all 0.3s ease',
    },
  },
  purple8: {
    backgroundColor: '$purple8',
    border: '1px solid $purple12',
    color: '$purple12',
    '&:active, &:focus-visible': { outlineColor: '$purple12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple12',
      transition: 'all 0.3s ease',
    },
  },
  purple9: {
    backgroundColor: '$purple9',
    border: '1px solid $purple1',
    color: '$purple1',
    '&:active, &:focus-visible': { outlineColor: '$purple1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple1',
      transition: 'all 0.3s ease',
    },
  },
  purple10: {
    backgroundColor: '$purple10',
    border: '1px solid $purple1',
    color: '$purple1',
    '&:active, &:focus-visible': { outlineColor: '$purple1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple1',
      transition: 'all 0.3s ease',
    },
  },
  purple11: {
    backgroundColor: '$purple11',
    border: '1px solid $purple1',
    color: '$purple1',
    '&:active, &:focus-visible': { outlineColor: '$purple1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple1',
      transition: 'all 0.3s ease',
    },
  },
  purple12: {
    backgroundColor: '$purple12',
    border: '1px solid $purple1',
    color: '$purple1',
    '&:active, &:focus-visible': { outlineColor: '$purple1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$purple1',
      transition: 'all 0.3s ease',
    },
  },
  green1: {
    backgroundColor: '$green1',
    border: '1px solid $green12',
    color: '$green12',
    '&:active, &:focus-visible': { outlineColor: '$green12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green12',
      transition: 'all 0.3s ease',
    },
  },
  green2: {
    backgroundColor: '$green2',
    border: '1px solid $green12',
    color: '$green12',
    '&:active, &:focus-visible': { outlineColor: '$green12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green12',
      transition: 'all 0.3s ease',
    },
  },
  green3: {
    backgroundColor: '$green3',
    border: '1px solid $green12',
    color: '$green12',
    '&:active, &:focus-visible': { outlineColor: '$green12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green12',
      transition: 'all 0.3s ease',
    },
  },
  green4: {
    backgroundColor: '$green4',
    border: '1px solid $green12',
    color: '$green12',
    '&:active, &:focus-visible': { outlineColor: '$green12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green12',
      transition: 'all 0.3s ease',
    },
  },
  green5: {
    backgroundColor: '$green5',
    border: '1px solid $green11',
    color: '$green11',
    '&:active, &:focus-visible': { outlineColor: '$green11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green11',
      transition: 'all 0.3s ease',
    },
  },
  green6: {
    backgroundColor: '$green6',
    border: '1px solid $green11',
    color: '$green11',
    '&:active, &:focus-visible': { outlineColor: '$green11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green11',
      transition: 'all 0.3s ease',
    },
  },
  green7: {
    backgroundColor: '$green7',
    border: '1px solid $green12',
    color: '$green12',
    '&:active, &:focus-visible': { outlineColor: '$green12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green12',
      transition: 'all 0.3s ease',
    },
  },
  green8: {
    backgroundColor: '$green8',
    border: '1px solid $green12',
    color: '$green12',
    '&:active, &:focus-visible': { outlineColor: '$green12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green12',
      transition: 'all 0.3s ease',
    },
  },
  green9: {
    backgroundColor: '$green9',
    border: '1px solid $green1',
    color: '$green1',
    '&:active, &:focus-visible': { outlineColor: '$green1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green1',
      transition: 'all 0.3s ease',
    },
  },
  green10: {
    backgroundColor: '$green10',
    border: '1px solid $green1',
    color: '$green1',
    '&:active, &:focus-visible': { outlineColor: '$green1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green1',
      transition: 'all 0.3s ease',
    },
  },
  green11: {
    backgroundColor: '$green11',
    border: '1px solid $green1',
    color: '$green1',
    '&:active, &:focus-visible': { outlineColor: '$green1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green1',
      transition: 'all 0.3s ease',
    },
  },
  green12: {
    backgroundColor: '$green12',
    border: '1px solid $green1',
    color: '$green1',
    '&:active, &:focus-visible': { outlineColor: '$green1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$green1',
      transition: 'all 0.3s ease',
    },
  },
  blue1: {
    backgroundColor: '$blue1',
    border: '1px solid $blue12',
    color: '$blue12',
    '&:active, &:focus-visible': { outlineColor: '$blue12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue12',
      transition: 'all 0.3s ease',
    },
  },
  blue2: {
    backgroundColor: '$blue2',
    border: '1px solid $blue12',
    color: '$blue12',
    '&:active, &:focus-visible': { outlineColor: '$blue12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue12',
      transition: 'all 0.3s ease',
    },
  },
  blue3: {
    backgroundColor: '$blue3',
    border: '1px solid $blue12',
    color: '$blue12',
    '&:active, &:focus-visible': { outlineColor: '$blue12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue12',
      transition: 'all 0.3s ease',
    },
  },
  blue4: {
    backgroundColor: '$blue4',
    border: '1px solid $blue12',
    color: '$blue12',
    '&:active, &:focus-visible': { outlineColor: '$blue12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue12',
      transition: 'all 0.3s ease',
    },
  },
  blue5: {
    backgroundColor: '$blue5',
    border: '1px solid $blue11',
    color: '$blue11',
    '&:active, &:focus-visible': { outlineColor: '$blue11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue11',
      transition: 'all 0.3s ease',
    },
  },
  blue6: {
    backgroundColor: '$blue6',
    border: '1px solid $blue11',
    color: '$blue11',
    '&:active, &:focus-visible': { outlineColor: '$blue11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue11',
      transition: 'all 0.3s ease',
    },
  },
  blue7: {
    backgroundColor: '$blue7',
    border: '1px solid $blue12',
    color: '$blue12',
    '&:active, &:focus-visible': { outlineColor: '$blue12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue12',
      transition: 'all 0.3s ease',
    },
  },
  blue8: {
    backgroundColor: '$blue8',
    border: '1px solid $blue12',
    color: '$blue12',
    '&:active, &:focus-visible': { outlineColor: '$blue12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue12',
      transition: 'all 0.3s ease',
    },
  },
  blue9: {
    backgroundColor: '$blue9',
    border: '1px solid $blue1',
    color: '$blue1',
    '&:active, &:focus-visible': { outlineColor: '$blue1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue1',
      transition: 'all 0.3s ease',
    },
  },
  blue10: {
    backgroundColor: '$blue10',
    border: '1px solid $blue1',
    color: '$blue1',
    '&:active, &:focus-visible': { outlineColor: '$blue1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue1',
      transition: 'all 0.3s ease',
    },
  },
  blue11: {
    backgroundColor: '$blue11',
    border: '1px solid $blue1',
    color: '$blue1',
    '&:active, &:focus-visible': { outlineColor: '$blue1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue1',
      transition: 'all 0.3s ease',
    },
  },
  blue12: {
    backgroundColor: '$blue12',
    border: '1px solid $blue1',
    color: '$blue1',
    '&:active, &:focus-visible': { outlineColor: '$blue1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$blue1',
      transition: 'all 0.3s ease',
    },
  },
  red1: {
    backgroundColor: '$red1',
    border: '1px solid $red12',
    color: '$red12',
    '&:active, &:focus-visible': { outlineColor: '$red12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red12',
      transition: 'all 0.3s ease',
    },
  },
  red2: {
    backgroundColor: '$red2',
    border: '1px solid $red12',
    color: '$red12',
    '&:active, &:focus-visible': { outlineColor: '$red12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red12',
      transition: 'all 0.3s ease',
    },
  },
  red3: {
    backgroundColor: '$red3',
    border: '1px solid $red12',
    color: '$red12',
    '&:active, &:focus-visible': { outlineColor: '$red12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red12',
      transition: 'all 0.3s ease',
    },
  },
  red4: {
    backgroundColor: '$red4',
    border: '1px solid $red12',
    color: '$red12',
    '&:active, &:focus-visible': { outlineColor: '$red12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red12',
      transition: 'all 0.3s ease',
    },
  },
  red5: {
    backgroundColor: '$red5',
    border: '1px solid $red11',
    color: '$red11',
    '&:active, &:focus-visible': { outlineColor: '$red11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red11',
      transition: 'all 0.3s ease',
    },
  },
  red6: {
    backgroundColor: '$red6',
    border: '1px solid $red11',
    color: '$red11',
    '&:active, &:focus-visible': { outlineColor: '$red11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red11',
      transition: 'all 0.3s ease',
    },
  },
  red7: {
    backgroundColor: '$red7',
    border: '1px solid $red12',
    color: '$red12',
    '&:active, &:focus-visible': { outlineColor: '$red12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red12',
      transition: 'all 0.3s ease',
    },
  },
  red8: {
    backgroundColor: '$red8',
    border: '1px solid $red12',
    color: '$red12',
    '&:active, &:focus-visible': { outlineColor: '$red12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red12',
      transition: 'all 0.3s ease',
    },
  },
  red9: {
    backgroundColor: '$red9',
    border: '1px solid $red1',
    color: '$red1',
    '&:active, &:focus-visible': { outlineColor: '$red1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red1',
      transition: 'all 0.3s ease',
    },
  },
  red10: {
    backgroundColor: '$red10',
    border: '1px solid $red1',
    color: '$red1',
    '&:active, &:focus-visible': { outlineColor: '$red1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red1',
      transition: 'all 0.3s ease',
    },
  },
  red11: {
    backgroundColor: '$red11',
    border: '1px solid $red1',
    color: '$red1',
    '&:active, &:focus-visible': { outlineColor: '$red1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red1',
      transition: 'all 0.3s ease',
    },
  },
  red12: {
    backgroundColor: '$red12',
    border: '1px solid $red1',
    color: '$red1',
    '&:active, &:focus-visible': { outlineColor: '$red1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$red1',
      transition: 'all 0.3s ease',
    },
  },
  yellow1: {
    backgroundColor: '$yellow1',
    border: '1px solid $yellow12',
    color: '$yellow12',
    '&:active, &:focus-visible': { outlineColor: '$yellow12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow12',
      transition: 'all 0.3s ease',
    },
  },
  yellow2: {
    backgroundColor: '$yellow2',
    border: '1px solid $yellow12',
    color: '$yellow12',
    '&:active, &:focus-visible': { outlineColor: '$yellow12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow12',
      transition: 'all 0.3s ease',
    },
  },
  yellow3: {
    backgroundColor: '$yellow3',
    border: '1px solid $yellow12',
    color: '$yellow12',
    '&:active, &:focus-visible': { outlineColor: '$yellow12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow12',
      transition: 'all 0.3s ease',
    },
  },
  yellow4: {
    backgroundColor: '$yellow4',
    border: '1px solid $yellow12',
    color: '$yellow12',
    '&:active, &:focus-visible': { outlineColor: '$yellow12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow12',
      transition: 'all 0.3s ease',
    },
  },
  yellow5: {
    backgroundColor: '$yellow5',
    border: '1px solid $yellow11',
    color: '$yellow11',
    '&:active, &:focus-visible': { outlineColor: '$yellow11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow11',
      transition: 'all 0.3s ease',
    },
  },
  yellow6: {
    backgroundColor: '$yellow6',
    border: '1px solid $yellow11',
    color: '$yellow11',
    '&:active, &:focus-visible': { outlineColor: '$yellow11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow11',
      transition: 'all 0.3s ease',
    },
  },
  yellow7: {
    backgroundColor: '$yellow7',
    border: '1px solid $yellow12',
    color: '$yellow12',
    '&:active, &:focus-visible': { outlineColor: '$yellow12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow12',
      transition: 'all 0.3s ease',
    },
  },
  yellow8: {
    backgroundColor: '$yellow8',
    border: '1px solid $yellow12',
    color: '$yellow12',
    '&:active, &:focus-visible': { outlineColor: '$yellow12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow12',
      transition: 'all 0.3s ease',
    },
  },
  yellow9: {
    backgroundColor: '$yellow9',
    border: '1px solid $yellow1',
    color: '$yellow1',
    '&:active, &:focus-visible': { outlineColor: '$yellow1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow1',
      transition: 'all 0.3s ease',
    },
  },
  yellow10: {
    backgroundColor: '$yellow10',
    border: '1px solid $yellow1',
    color: '$yellow1',
    '&:active, &:focus-visible': { outlineColor: '$yellow1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow1',
      transition: 'all 0.3s ease',
    },
  },
  yellow11: {
    backgroundColor: '$yellow11',
    border: '1px solid $yellow1',
    color: '$yellow1',
    '&:active, &:focus-visible': { outlineColor: '$yellow1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow1',
      transition: 'all 0.3s ease',
    },
  },
  yellow12: {
    backgroundColor: '$yellow12',
    border: '1px solid $yellow1',
    color: '$yellow1',
    '&:active, &:focus-visible': { outlineColor: '$yellow1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$yellow1',
      transition: 'all 0.3s ease',
    },
  },
  orange1: {
    backgroundColor: '$orange1',
    border: '1px solid $orange12',
    color: '$orange12',
    '&:active, &:focus-visible': { outlineColor: '$orange12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange12',
      transition: 'all 0.3s ease',
    },
  },
  orange2: {
    backgroundColor: '$orange2',
    border: '1px solid $orange12',
    color: '$orange12',
    '&:active, &:focus-visible': { outlineColor: '$orange12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange12',
      transition: 'all 0.3s ease',
    },
  },
  orange3: {
    backgroundColor: '$orange3',
    border: '1px solid $orange12',
    color: '$orange12',
    '&:active, &:focus-visible': { outlineColor: '$orange12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange12',
      transition: 'all 0.3s ease',
    },
  },
  orange4: {
    backgroundColor: '$orange4',
    border: '1px solid $orange12',
    color: '$orange12',
    '&:active, &:focus-visible': { outlineColor: '$orange12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange12',
      transition: 'all 0.3s ease',
    },
  },
  orange5: {
    backgroundColor: '$orange5',
    border: '1px solid $orange11',
    color: '$orange11',
    '&:active, &:focus-visible': { outlineColor: '$orange11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange11',
      transition: 'all 0.3s ease',
    },
  },
  orange6: {
    backgroundColor: '$orange6',
    border: '1px solid $orange11',
    color: '$orange11',
    '&:active, &:focus-visible': { outlineColor: '$orange11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange11',
      transition: 'all 0.3s ease',
    },
  },
  orange7: {
    backgroundColor: '$orange7',
    border: '1px solid $orange12',
    color: '$orange12',
    '&:active, &:focus-visible': { outlineColor: '$orange12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange12',
      transition: 'all 0.3s ease',
    },
  },
  orange8: {
    backgroundColor: '$orange8',
    border: '1px solid $orange12',
    color: '$orange12',
    '&:active, &:focus-visible': { outlineColor: '$orange12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange12',
      transition: 'all 0.3s ease',
    },
  },
  orange9: {
    backgroundColor: '$orange9',
    border: '1px solid $orange1',
    color: '$orange1',
    '&:active, &:focus-visible': { outlineColor: '$orange1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange1',
      transition: 'all 0.3s ease',
    },
  },
  orange10: {
    backgroundColor: '$orange10',
    border: '1px solid $orange1',
    color: '$orange1',
    '&:active, &:focus-visible': { outlineColor: '$orange1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange1',
      transition: 'all 0.3s ease',
    },
  },
  orange11: {
    backgroundColor: '$orange11',
    border: '1px solid $orange1',
    color: '$orange1',
    '&:active, &:focus-visible': { outlineColor: '$orange1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange1',
      transition: 'all 0.3s ease',
    },
  },
  orange12: {
    backgroundColor: '$orange12',
    border: '1px solid $orange1',
    color: '$orange1',
    '&:active, &:focus-visible': { outlineColor: '$orange1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$orange1',
      transition: 'all 0.3s ease',
    },
  },
  gray1: {
    backgroundColor: '$gray1',
    border: '1px solid $gray12',
    color: '$gray12',
    '&:active, &:focus-visible': { outlineColor: '$gray12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray12',
      transition: 'all 0.3s ease',
    },
  },
  gray2: {
    backgroundColor: '$gray2',
    border: '1px solid $gray12',
    color: '$gray12',
    '&:active, &:focus-visible': { outlineColor: '$gray12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray12',
      transition: 'all 0.3s ease',
    },
  },
  gray3: {
    backgroundColor: '$gray3',
    border: '1px solid $gray12',
    color: '$gray12',
    '&:active, &:focus-visible': { outlineColor: '$gray12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray12',
      transition: 'all 0.3s ease',
    },
  },
  gray4: {
    backgroundColor: '$gray4',
    border: '1px solid $gray12',
    color: '$gray12',
    '&:active, &:focus-visible': { outlineColor: '$gray12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray12',
      transition: 'all 0.3s ease',
    },
  },
  gray5: {
    backgroundColor: '$gray5',
    border: '1px solid $gray11',
    color: '$gray11',
    '&:active, &:focus-visible': { outlineColor: '$gray11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray11',
      transition: 'all 0.3s ease',
    },
  },
  gray6: {
    backgroundColor: '$gray6',
    border: '1px solid $gray11',
    color: '$gray11',
    '&:active, &:focus-visible': { outlineColor: '$gray11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray11',
      transition: 'all 0.3s ease',
    },
  },
  gray7: {
    backgroundColor: '$gray7',
    border: '1px solid $gray12',
    color: '$gray12',
    '&:active, &:focus-visible': { outlineColor: '$gray12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray12',
      transition: 'all 0.3s ease',
    },
  },
  gray8: {
    backgroundColor: '$gray8',
    border: '1px solid $gray12',
    color: '$gray12',
    '&:active, &:focus-visible': { outlineColor: '$gray12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray12',
      transition: 'all 0.3s ease',
    },
  },
  gray9: {
    backgroundColor: '$gray9',
    border: '1px solid $gray1',
    color: '$gray1',
    '&:active, &:focus-visible': { outlineColor: '$gray1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray1',
      transition: 'all 0.3s ease',
    },
  },
  gray10: {
    backgroundColor: '$gray10',
    border: '1px solid $gray1',
    color: '$gray1',
    '&:active, &:focus-visible': { outlineColor: '$gray1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray1',
      transition: 'all 0.3s ease',
    },
  },
  gray11: {
    backgroundColor: '$gray11',
    border: '1px solid $gray1',
    color: '$gray1',
    '&:active, &:focus-visible': { outlineColor: '$gray1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray1',
      transition: 'all 0.3s ease',
    },
  },
  gray12: {
    backgroundColor: '$gray12',
    border: '1px solid $gray1',
    color: '$gray1',
    '&:active, &:focus-visible': { outlineColor: '$gray1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gray1',
      transition: 'all 0.3s ease',
    },
  },
  tomato1: {
    backgroundColor: '$tomato1',
    border: '1px solid $tomato12',
    color: '$tomato12',
    '&:active, &:focus-visible': { outlineColor: '$tomato12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato12',
      transition: 'all 0.3s ease',
    },
  },
  tomato2: {
    backgroundColor: '$tomato2',
    border: '1px solid $tomato12',
    color: '$tomato12',
    '&:active, &:focus-visible': { outlineColor: '$tomato12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato12',
      transition: 'all 0.3s ease',
    },
  },
  tomato3: {
    backgroundColor: '$tomato3',
    border: '1px solid $tomato12',
    color: '$tomato12',
    '&:active, &:focus-visible': { outlineColor: '$tomato12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato12',
      transition: 'all 0.3s ease',
    },
  },
  tomato4: {
    backgroundColor: '$tomato4',
    border: '1px solid $tomato12',
    color: '$tomato12',
    '&:active, &:focus-visible': { outlineColor: '$tomato12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato12',
      transition: 'all 0.3s ease',
    },
  },
  tomato5: {
    backgroundColor: '$tomato5',
    border: '1px solid $tomato11',
    color: '$tomato11',
    '&:active, &:focus-visible': { outlineColor: '$tomato11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato11',
      transition: 'all 0.3s ease',
    },
  },
  tomato6: {
    backgroundColor: '$tomato6',
    border: '1px solid $tomato11',
    color: '$tomato11',
    '&:active, &:focus-visible': { outlineColor: '$tomato11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato11',
      transition: 'all 0.3s ease',
    },
  },
  tomato7: {
    backgroundColor: '$tomato7',
    border: '1px solid $tomato12',
    color: '$tomato12',
    '&:active, &:focus-visible': { outlineColor: '$tomato12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato12',
      transition: 'all 0.3s ease',
    },
  },
  tomato8: {
    backgroundColor: '$tomato8',
    border: '1px solid $tomato12',
    color: '$tomato12',
    '&:active, &:focus-visible': { outlineColor: '$tomato12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato12',
      transition: 'all 0.3s ease',
    },
  },
  tomato9: {
    backgroundColor: '$tomato9',
    border: '1px solid $tomato1',
    color: '$tomato1',
    '&:active, &:focus-visible': { outlineColor: '$tomato1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato1',
      transition: 'all 0.3s ease',
    },
  },
  tomato10: {
    backgroundColor: '$tomato10',
    border: '1px solid $tomato1',
    color: '$tomato1',
    '&:active, &:focus-visible': { outlineColor: '$tomato1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato1',
      transition: 'all 0.3s ease',
    },
  },
  tomato11: {
    backgroundColor: '$tomato11',
    border: '1px solid $tomato1',
    color: '$tomato1',
    '&:active, &:focus-visible': { outlineColor: '$tomato1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato1',
      transition: 'all 0.3s ease',
    },
  },
  tomato12: {
    backgroundColor: '$tomato12',
    border: '1px solid $tomato1',
    color: '$tomato1',
    '&:active, &:focus-visible': { outlineColor: '$tomato1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$tomato1',
      transition: 'all 0.3s ease',
    },
  },
  crimson1: {
    backgroundColor: '$crimson1',
    border: '1px solid $crimson12',
    color: '$crimson12',
    '&:active, &:focus-visible': { outlineColor: '$crimson12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson12',
      transition: 'all 0.3s ease',
    },
  },
  crimson2: {
    backgroundColor: '$crimson2',
    border: '1px solid $crimson12',
    color: '$crimson12',
    '&:active, &:focus-visible': { outlineColor: '$crimson12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson12',
      transition: 'all 0.3s ease',
    },
  },
  crimson3: {
    backgroundColor: '$crimson3',
    border: '1px solid $crimson12',
    color: '$crimson12',
    '&:active, &:focus-visible': { outlineColor: '$crimson12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson12',
      transition: 'all 0.3s ease',
    },
  },
  crimson4: {
    backgroundColor: '$crimson4',
    border: '1px solid $crimson12',
    color: '$crimson12',
    '&:active, &:focus-visible': { outlineColor: '$crimson12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson12',
      transition: 'all 0.3s ease',
    },
  },
  crimson5: {
    backgroundColor: '$crimson5',
    border: '1px solid $crimson11',
    color: '$crimson11',
    '&:active, &:focus-visible': { outlineColor: '$crimson11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson11',
      transition: 'all 0.3s ease',
    },
  },
  crimson6: {
    backgroundColor: '$crimson6',
    border: '1px solid $crimson11',
    color: '$crimson11',
    '&:active, &:focus-visible': { outlineColor: '$crimson11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson11',
      transition: 'all 0.3s ease',
    },
  },
  crimson7: {
    backgroundColor: '$crimson7',
    border: '1px solid $crimson12',
    color: '$crimson12',
    '&:active, &:focus-visible': { outlineColor: '$crimson12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson12',
      transition: 'all 0.3s ease',
    },
  },
  crimson8: {
    backgroundColor: '$crimson8',
    border: '1px solid $crimson12',
    color: '$crimson12',
    '&:active, &:focus-visible': { outlineColor: '$crimson12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson12',
      transition: 'all 0.3s ease',
    },
  },
  crimson9: {
    backgroundColor: '$crimson9',
    border: '1px solid $crimson1',
    color: '$crimson1',
    '&:active, &:focus-visible': { outlineColor: '$crimson1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson1',
      transition: 'all 0.3s ease',
    },
  },
  crimson10: {
    backgroundColor: '$crimson10',
    border: '1px solid $crimson1',
    color: '$crimson1',
    '&:active, &:focus-visible': { outlineColor: '$crimson1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson1',
      transition: 'all 0.3s ease',
    },
  },
  crimson11: {
    backgroundColor: '$crimson11',
    border: '1px solid $crimson1',
    color: '$crimson1',
    '&:active, &:focus-visible': { outlineColor: '$crimson1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson1',
      transition: 'all 0.3s ease',
    },
  },
  crimson12: {
    backgroundColor: '$crimson12',
    border: '1px solid $crimson1',
    color: '$crimson1',
    '&:active, &:focus-visible': { outlineColor: '$crimson1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$crimson1',
      transition: 'all 0.3s ease',
    },
  },
  pink1: {
    backgroundColor: '$pink1',
    border: '1px solid $pink12',
    color: '$pink12',
    '&:active, &:focus-visible': { outlineColor: '$pink12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink12',
      transition: 'all 0.3s ease',
    },
  },
  pink2: {
    backgroundColor: '$pink2',
    border: '1px solid $pink12',
    color: '$pink12',
    '&:active, &:focus-visible': { outlineColor: '$pink12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink12',
      transition: 'all 0.3s ease',
    },
  },
  pink3: {
    backgroundColor: '$pink3',
    border: '1px solid $pink12',
    color: '$pink12',
    '&:active, &:focus-visible': { outlineColor: '$pink12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink12',
      transition: 'all 0.3s ease',
    },
  },
  pink4: {
    backgroundColor: '$pink4',
    border: '1px solid $pink12',
    color: '$pink12',
    '&:active, &:focus-visible': { outlineColor: '$pink12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink12',
      transition: 'all 0.3s ease',
    },
  },
  pink5: {
    backgroundColor: '$pink5',
    border: '1px solid $pink11',
    color: '$pink11',
    '&:active, &:focus-visible': { outlineColor: '$pink11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink11',
      transition: 'all 0.3s ease',
    },
  },
  pink6: {
    backgroundColor: '$pink6',
    border: '1px solid $pink11',
    color: '$pink11',
    '&:active, &:focus-visible': { outlineColor: '$pink11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink11',
      transition: 'all 0.3s ease',
    },
  },
  pink7: {
    backgroundColor: '$pink7',
    border: '1px solid $pink12',
    color: '$pink12',
    '&:active, &:focus-visible': { outlineColor: '$pink12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink12',
      transition: 'all 0.3s ease',
    },
  },
  pink8: {
    backgroundColor: '$pink8',
    border: '1px solid $pink12',
    color: '$pink12',
    '&:active, &:focus-visible': { outlineColor: '$pink12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink12',
      transition: 'all 0.3s ease',
    },
  },
  pink9: {
    backgroundColor: '$pink9',
    border: '1px solid $pink1',
    color: '$pink1',
    '&:active, &:focus-visible': { outlineColor: '$pink1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink1',
      transition: 'all 0.3s ease',
    },
  },
  pink10: {
    backgroundColor: '$pink10',
    border: '1px solid $pink1',
    color: '$pink1',
    '&:active, &:focus-visible': { outlineColor: '$pink1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink1',
      transition: 'all 0.3s ease',
    },
  },
  pink11: {
    backgroundColor: '$pink11',
    border: '1px solid $pink1',
    color: '$pink1',
    '&:active, &:focus-visible': { outlineColor: '$pink1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink1',
      transition: 'all 0.3s ease',
    },
  },
  pink12: {
    backgroundColor: '$pink12',
    border: '1px solid $pink1',
    color: '$pink1',
    '&:active, &:focus-visible': { outlineColor: '$pink1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$pink1',
      transition: 'all 0.3s ease',
    },
  },
  plum1: {
    backgroundColor: '$plum1',
    border: '1px solid $plum12',
    color: '$plum12',
    '&:active, &:focus-visible': { outlineColor: '$plum12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum12',
      transition: 'all 0.3s ease',
    },
  },
  plum2: {
    backgroundColor: '$plum2',
    border: '1px solid $plum12',
    color: '$plum12',
    '&:active, &:focus-visible': { outlineColor: '$plum12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum12',
      transition: 'all 0.3s ease',
    },
  },
  plum3: {
    backgroundColor: '$plum3',
    border: '1px solid $plum12',
    color: '$plum12',
    '&:active, &:focus-visible': { outlineColor: '$plum12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum12',
      transition: 'all 0.3s ease',
    },
  },
  plum4: {
    backgroundColor: '$plum4',
    border: '1px solid $plum12',
    color: '$plum12',
    '&:active, &:focus-visible': { outlineColor: '$plum12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum12',
      transition: 'all 0.3s ease',
    },
  },
  plum5: {
    backgroundColor: '$plum5',
    border: '1px solid $plum11',
    color: '$plum11',
    '&:active, &:focus-visible': { outlineColor: '$plum11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum11',
      transition: 'all 0.3s ease',
    },
  },
  plum6: {
    backgroundColor: '$plum6',
    border: '1px solid $plum11',
    color: '$plum11',
    '&:active, &:focus-visible': { outlineColor: '$plum11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum11',
      transition: 'all 0.3s ease',
    },
  },
  plum7: {
    backgroundColor: '$plum7',
    border: '1px solid $plum12',
    color: '$plum12',
    '&:active, &:focus-visible': { outlineColor: '$plum12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum12',
      transition: 'all 0.3s ease',
    },
  },
  plum8: {
    backgroundColor: '$plum8',
    border: '1px solid $plum12',
    color: '$plum12',
    '&:active, &:focus-visible': { outlineColor: '$plum12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum12',
      transition: 'all 0.3s ease',
    },
  },
  plum9: {
    backgroundColor: '$plum9',
    border: '1px solid $plum1',
    color: '$plum1',
    '&:active, &:focus-visible': { outlineColor: '$plum1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum1',
      transition: 'all 0.3s ease',
    },
  },
  plum10: {
    backgroundColor: '$plum10',
    border: '1px solid $plum1',
    color: '$plum1',
    '&:active, &:focus-visible': { outlineColor: '$plum1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum1',
      transition: 'all 0.3s ease',
    },
  },
  plum11: {
    backgroundColor: '$plum11',
    border: '1px solid $plum1',
    color: '$plum1',
    '&:active, &:focus-visible': { outlineColor: '$plum1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum1',
      transition: 'all 0.3s ease',
    },
  },
  plum12: {
    backgroundColor: '$plum12',
    border: '1px solid $plum1',
    color: '$plum1',
    '&:active, &:focus-visible': { outlineColor: '$plum1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$plum1',
      transition: 'all 0.3s ease',
    },
  },
  violet1: {
    backgroundColor: '$violet1',
    border: '1px solid $violet12',
    color: '$violet12',
    '&:active, &:focus-visible': { outlineColor: '$violet12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet12',
      transition: 'all 0.3s ease',
    },
  },
  violet2: {
    backgroundColor: '$violet2',
    border: '1px solid $violet12',
    color: '$violet12',
    '&:active, &:focus-visible': { outlineColor: '$violet12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet12',
      transition: 'all 0.3s ease',
    },
  },
  violet3: {
    backgroundColor: '$violet3',
    border: '1px solid $violet12',
    color: '$violet12',
    '&:active, &:focus-visible': { outlineColor: '$violet12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet12',
      transition: 'all 0.3s ease',
    },
  },
  violet4: {
    backgroundColor: '$violet4',
    border: '1px solid $violet12',
    color: '$violet12',
    '&:active, &:focus-visible': { outlineColor: '$violet12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet12',
      transition: 'all 0.3s ease',
    },
  },
  violet5: {
    backgroundColor: '$violet5',
    border: '1px solid $violet11',
    color: '$violet11',
    '&:active, &:focus-visible': { outlineColor: '$violet11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet11',
      transition: 'all 0.3s ease',
    },
  },
  violet6: {
    backgroundColor: '$violet6',
    border: '1px solid $violet11',
    color: '$violet11',
    '&:active, &:focus-visible': { outlineColor: '$violet11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet11',
      transition: 'all 0.3s ease',
    },
  },
  violet7: {
    backgroundColor: '$violet7',
    border: '1px solid $violet12',
    color: '$violet12',
    '&:active, &:focus-visible': { outlineColor: '$violet12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet12',
      transition: 'all 0.3s ease',
    },
  },
  violet8: {
    backgroundColor: '$violet8',
    border: '1px solid $violet12',
    color: '$violet12',
    '&:active, &:focus-visible': { outlineColor: '$violet12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet12',
      transition: 'all 0.3s ease',
    },
  },
  violet9: {
    backgroundColor: '$violet9',
    border: '1px solid $violet1',
    color: '$violet1',
    '&:active, &:focus-visible': { outlineColor: '$violet1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet1',
      transition: 'all 0.3s ease',
    },
  },
  violet10: {
    backgroundColor: '$violet10',
    border: '1px solid $violet1',
    color: '$violet1',
    '&:active, &:focus-visible': { outlineColor: '$violet1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet1',
      transition: 'all 0.3s ease',
    },
  },
  violet11: {
    backgroundColor: '$violet11',
    border: '1px solid $violet1',
    color: '$violet1',
    '&:active, &:focus-visible': { outlineColor: '$violet1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet1',
      transition: 'all 0.3s ease',
    },
  },
  violet12: {
    backgroundColor: '$violet12',
    border: '1px solid $violet1',
    color: '$violet1',
    '&:active, &:focus-visible': { outlineColor: '$violet1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$violet1',
      transition: 'all 0.3s ease',
    },
  },
  indigo1: {
    backgroundColor: '$indigo1',
    border: '1px solid $indigo12',
    color: '$indigo12',
    '&:active, &:focus-visible': { outlineColor: '$indigo12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo12',
      transition: 'all 0.3s ease',
    },
  },
  indigo2: {
    backgroundColor: '$indigo2',
    border: '1px solid $indigo12',
    color: '$indigo12',
    '&:active, &:focus-visible': { outlineColor: '$indigo12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo12',
      transition: 'all 0.3s ease',
    },
  },
  indigo3: {
    backgroundColor: '$indigo3',
    border: '1px solid $indigo12',
    color: '$indigo12',
    '&:active, &:focus-visible': { outlineColor: '$indigo12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo12',
      transition: 'all 0.3s ease',
    },
  },
  indigo4: {
    backgroundColor: '$indigo4',
    border: '1px solid $indigo12',
    color: '$indigo12',
    '&:active, &:focus-visible': { outlineColor: '$indigo12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo12',
      transition: 'all 0.3s ease',
    },
  },
  indigo5: {
    backgroundColor: '$indigo5',
    border: '1px solid $indigo11',
    color: '$indigo11',
    '&:active, &:focus-visible': { outlineColor: '$indigo11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo11',
      transition: 'all 0.3s ease',
    },
  },
  indigo6: {
    backgroundColor: '$indigo6',
    border: '1px solid $indigo11',
    color: '$indigo11',
    '&:active, &:focus-visible': { outlineColor: '$indigo11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo11',
      transition: 'all 0.3s ease',
    },
  },
  indigo7: {
    backgroundColor: '$indigo7',
    border: '1px solid $indigo12',
    color: '$indigo12',
    '&:active, &:focus-visible': { outlineColor: '$indigo12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo12',
      transition: 'all 0.3s ease',
    },
  },
  indigo8: {
    backgroundColor: '$indigo8',
    border: '1px solid $indigo12',
    color: '$indigo12',
    '&:active, &:focus-visible': { outlineColor: '$indigo12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo12',
      transition: 'all 0.3s ease',
    },
  },
  indigo9: {
    backgroundColor: '$indigo9',
    border: '1px solid $indigo1',
    color: '$indigo1',
    '&:active, &:focus-visible': { outlineColor: '$indigo1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo1',
      transition: 'all 0.3s ease',
    },
  },
  indigo10: {
    backgroundColor: '$indigo10',
    border: '1px solid $indigo1',
    color: '$indigo1',
    '&:active, &:focus-visible': { outlineColor: '$indigo1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo1',
      transition: 'all 0.3s ease',
    },
  },
  indigo11: {
    backgroundColor: '$indigo11',
    border: '1px solid $indigo1',
    color: '$indigo1',
    '&:active, &:focus-visible': { outlineColor: '$indigo1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo1',
      transition: 'all 0.3s ease',
    },
  },
  indigo12: {
    backgroundColor: '$indigo12',
    border: '1px solid $indigo1',
    color: '$indigo1',
    '&:active, &:focus-visible': { outlineColor: '$indigo1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$indigo1',
      transition: 'all 0.3s ease',
    },
  },
  cyan1: {
    backgroundColor: '$cyan1',
    border: '1px solid $cyan12',
    color: '$cyan12',
    '&:active, &:focus-visible': { outlineColor: '$cyan12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan12',
      transition: 'all 0.3s ease',
    },
  },
  cyan2: {
    backgroundColor: '$cyan2',
    border: '1px solid $cyan12',
    color: '$cyan12',
    '&:active, &:focus-visible': { outlineColor: '$cyan12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan12',
      transition: 'all 0.3s ease',
    },
  },
  cyan3: {
    backgroundColor: '$cyan3',
    border: '1px solid $cyan12',
    color: '$cyan12',
    '&:active, &:focus-visible': { outlineColor: '$cyan12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan12',
      transition: 'all 0.3s ease',
    },
  },
  cyan4: {
    backgroundColor: '$cyan4',
    border: '1px solid $cyan12',
    color: '$cyan12',
    '&:active, &:focus-visible': { outlineColor: '$cyan12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan12',
      transition: 'all 0.3s ease',
    },
  },
  cyan5: {
    backgroundColor: '$cyan5',
    border: '1px solid $cyan11',
    color: '$cyan11',
    '&:active, &:focus-visible': { outlineColor: '$cyan11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan11',
      transition: 'all 0.3s ease',
    },
  },
  cyan6: {
    backgroundColor: '$cyan6',
    border: '1px solid $cyan11',
    color: '$cyan11',
    '&:active, &:focus-visible': { outlineColor: '$cyan11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan11',
      transition: 'all 0.3s ease',
    },
  },
  cyan7: {
    backgroundColor: '$cyan7',
    border: '1px solid $cyan12',
    color: '$cyan12',
    '&:active, &:focus-visible': { outlineColor: '$cyan12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan12',
      transition: 'all 0.3s ease',
    },
  },
  cyan8: {
    backgroundColor: '$cyan8',
    border: '1px solid $cyan12',
    color: '$cyan12',
    '&:active, &:focus-visible': { outlineColor: '$cyan12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan12',
      transition: 'all 0.3s ease',
    },
  },
  cyan9: {
    backgroundColor: '$cyan9',
    border: '1px solid $cyan1',
    color: '$cyan1',
    '&:active, &:focus-visible': { outlineColor: '$cyan1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan1',
      transition: 'all 0.3s ease',
    },
  },
  cyan10: {
    backgroundColor: '$cyan10',
    border: '1px solid $cyan1',
    color: '$cyan1',
    '&:active, &:focus-visible': { outlineColor: '$cyan1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan1',
      transition: 'all 0.3s ease',
    },
  },
  cyan11: {
    backgroundColor: '$cyan11',
    border: '1px solid $cyan1',
    color: '$cyan1',
    '&:active, &:focus-visible': { outlineColor: '$cyan1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan1',
      transition: 'all 0.3s ease',
    },
  },
  cyan12: {
    backgroundColor: '$cyan12',
    border: '1px solid $cyan1',
    color: '$cyan1',
    '&:active, &:focus-visible': { outlineColor: '$cyan1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$cyan1',
      transition: 'all 0.3s ease',
    },
  },
  teal1: {
    backgroundColor: '$teal1',
    border: '1px solid $teal12',
    color: '$teal12',
    '&:active, &:focus-visible': { outlineColor: '$teal12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal12',
      transition: 'all 0.3s ease',
    },
  },
  teal2: {
    backgroundColor: '$teal2',
    border: '1px solid $teal12',
    color: '$teal12',
    '&:active, &:focus-visible': { outlineColor: '$teal12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal12',
      transition: 'all 0.3s ease',
    },
  },
  teal3: {
    backgroundColor: '$teal3',
    border: '1px solid $teal12',
    color: '$teal12',
    '&:active, &:focus-visible': { outlineColor: '$teal12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal12',
      transition: 'all 0.3s ease',
    },
  },
  teal4: {
    backgroundColor: '$teal4',
    border: '1px solid $teal12',
    color: '$teal12',
    '&:active, &:focus-visible': { outlineColor: '$teal12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal12',
      transition: 'all 0.3s ease',
    },
  },
  teal5: {
    backgroundColor: '$teal5',
    border: '1px solid $teal11',
    color: '$teal11',
    '&:active, &:focus-visible': { outlineColor: '$teal11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal11',
      transition: 'all 0.3s ease',
    },
  },
  teal6: {
    backgroundColor: '$teal6',
    border: '1px solid $teal11',
    color: '$teal11',
    '&:active, &:focus-visible': { outlineColor: '$teal11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal11',
      transition: 'all 0.3s ease',
    },
  },
  teal7: {
    backgroundColor: '$teal7',
    border: '1px solid $teal12',
    color: '$teal12',
    '&:active, &:focus-visible': { outlineColor: '$teal12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal12',
      transition: 'all 0.3s ease',
    },
  },
  teal8: {
    backgroundColor: '$teal8',
    border: '1px solid $teal12',
    color: '$teal12',
    '&:active, &:focus-visible': { outlineColor: '$teal12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal12',
      transition: 'all 0.3s ease',
    },
  },
  teal9: {
    backgroundColor: '$teal9',
    border: '1px solid $teal1',
    color: '$teal1',
    '&:active, &:focus-visible': { outlineColor: '$teal1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal1',
      transition: 'all 0.3s ease',
    },
  },
  teal10: {
    backgroundColor: '$teal10',
    border: '1px solid $teal1',
    color: '$teal1',
    '&:active, &:focus-visible': { outlineColor: '$teal1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal1',
      transition: 'all 0.3s ease',
    },
  },
  teal11: {
    backgroundColor: '$teal11',
    border: '1px solid $teal1',
    color: '$teal1',
    '&:active, &:focus-visible': { outlineColor: '$teal1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal1',
      transition: 'all 0.3s ease',
    },
  },
  teal12: {
    backgroundColor: '$teal12',
    border: '1px solid $teal1',
    color: '$teal1',
    '&:active, &:focus-visible': { outlineColor: '$teal1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$teal1',
      transition: 'all 0.3s ease',
    },
  },
  grass1: {
    backgroundColor: '$grass1',
    border: '1px solid $grass12',
    color: '$grass12',
    '&:active, &:focus-visible': { outlineColor: '$grass12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass12',
      transition: 'all 0.3s ease',
    },
  },
  grass2: {
    backgroundColor: '$grass2',
    border: '1px solid $grass12',
    color: '$grass12',
    '&:active, &:focus-visible': { outlineColor: '$grass12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass12',
      transition: 'all 0.3s ease',
    },
  },
  grass3: {
    backgroundColor: '$grass3',
    border: '1px solid $grass12',
    color: '$grass12',
    '&:active, &:focus-visible': { outlineColor: '$grass12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass12',
      transition: 'all 0.3s ease',
    },
  },
  grass4: {
    backgroundColor: '$grass4',
    border: '1px solid $grass12',
    color: '$grass12',
    '&:active, &:focus-visible': { outlineColor: '$grass12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass12',
      transition: 'all 0.3s ease',
    },
  },
  grass5: {
    backgroundColor: '$grass5',
    border: '1px solid $grass11',
    color: '$grass11',
    '&:active, &:focus-visible': { outlineColor: '$grass11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass11',
      transition: 'all 0.3s ease',
    },
  },
  grass6: {
    backgroundColor: '$grass6',
    border: '1px solid $grass11',
    color: '$grass11',
    '&:active, &:focus-visible': { outlineColor: '$grass11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass11',
      transition: 'all 0.3s ease',
    },
  },
  grass7: {
    backgroundColor: '$grass7',
    border: '1px solid $grass12',
    color: '$grass12',
    '&:active, &:focus-visible': { outlineColor: '$grass12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass12',
      transition: 'all 0.3s ease',
    },
  },
  grass8: {
    backgroundColor: '$grass8',
    border: '1px solid $grass12',
    color: '$grass12',
    '&:active, &:focus-visible': { outlineColor: '$grass12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass12',
      transition: 'all 0.3s ease',
    },
  },
  grass9: {
    backgroundColor: '$grass9',
    border: '1px solid $grass1',
    color: '$grass1',
    '&:active, &:focus-visible': { outlineColor: '$grass1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass1',
      transition: 'all 0.3s ease',
    },
  },
  grass10: {
    backgroundColor: '$grass10',
    border: '1px solid $grass1',
    color: '$grass1',
    '&:active, &:focus-visible': { outlineColor: '$grass1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass1',
      transition: 'all 0.3s ease',
    },
  },
  grass11: {
    backgroundColor: '$grass11',
    border: '1px solid $grass1',
    color: '$grass1',
    '&:active, &:focus-visible': { outlineColor: '$grass1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass1',
      transition: 'all 0.3s ease',
    },
  },
  grass12: {
    backgroundColor: '$grass12',
    border: '1px solid $grass1',
    color: '$grass1',
    '&:active, &:focus-visible': { outlineColor: '$grass1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$grass1',
      transition: 'all 0.3s ease',
    },
  },
  brown1: {
    backgroundColor: '$brown1',
    border: '1px solid $brown12',
    color: '$brown12',
    '&:active, &:focus-visible': { outlineColor: '$brown12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown12',
      transition: 'all 0.3s ease',
    },
  },
  brown2: {
    backgroundColor: '$brown2',
    border: '1px solid $brown12',
    color: '$brown12',
    '&:active, &:focus-visible': { outlineColor: '$brown12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown12',
      transition: 'all 0.3s ease',
    },
  },
  brown3: {
    backgroundColor: '$brown3',
    border: '1px solid $brown12',
    color: '$brown12',
    '&:active, &:focus-visible': { outlineColor: '$brown12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown12',
      transition: 'all 0.3s ease',
    },
  },
  brown4: {
    backgroundColor: '$brown4',
    border: '1px solid $brown12',
    color: '$brown12',
    '&:active, &:focus-visible': { outlineColor: '$brown12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown12',
      transition: 'all 0.3s ease',
    },
  },
  brown5: {
    backgroundColor: '$brown5',
    border: '1px solid $brown11',
    color: '$brown11',
    '&:active, &:focus-visible': { outlineColor: '$brown11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown11',
      transition: 'all 0.3s ease',
    },
  },
  brown6: {
    backgroundColor: '$brown6',
    border: '1px solid $brown11',
    color: '$brown11',
    '&:active, &:focus-visible': { outlineColor: '$brown11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown11',
      transition: 'all 0.3s ease',
    },
  },
  brown7: {
    backgroundColor: '$brown7',
    border: '1px solid $brown12',
    color: '$brown12',
    '&:active, &:focus-visible': { outlineColor: '$brown12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown12',
      transition: 'all 0.3s ease',
    },
  },
  brown8: {
    backgroundColor: '$brown8',
    border: '1px solid $brown12',
    color: '$brown12',
    '&:active, &:focus-visible': { outlineColor: '$brown12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown12',
      transition: 'all 0.3s ease',
    },
  },
  brown9: {
    backgroundColor: '$brown9',
    border: '1px solid $brown1',
    color: '$brown1',
    '&:active, &:focus-visible': { outlineColor: '$brown1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown1',
      transition: 'all 0.3s ease',
    },
  },
  brown10: {
    backgroundColor: '$brown10',
    border: '1px solid $brown1',
    color: '$brown1',
    '&:active, &:focus-visible': { outlineColor: '$brown1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown1',
      transition: 'all 0.3s ease',
    },
  },
  brown11: {
    backgroundColor: '$brown11',
    border: '1px solid $brown1',
    color: '$brown1',
    '&:active, &:focus-visible': { outlineColor: '$brown1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown1',
      transition: 'all 0.3s ease',
    },
  },
  brown12: {
    backgroundColor: '$brown12',
    border: '1px solid $brown1',
    color: '$brown1',
    '&:active, &:focus-visible': { outlineColor: '$brown1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$brown1',
      transition: 'all 0.3s ease',
    },
  },
  sky1: {
    backgroundColor: '$sky1',
    border: '1px solid $sky12',
    color: '$sky12',
    '&:active, &:focus-visible': { outlineColor: '$sky12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky12',
      transition: 'all 0.3s ease',
    },
  },
  sky2: {
    backgroundColor: '$sky2',
    border: '1px solid $sky12',
    color: '$sky12',
    '&:active, &:focus-visible': { outlineColor: '$sky12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky12',
      transition: 'all 0.3s ease',
    },
  },
  sky3: {
    backgroundColor: '$sky3',
    border: '1px solid $sky12',
    color: '$sky12',
    '&:active, &:focus-visible': { outlineColor: '$sky12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky12',
      transition: 'all 0.3s ease',
    },
  },
  sky4: {
    backgroundColor: '$sky4',
    border: '1px solid $sky12',
    color: '$sky12',
    '&:active, &:focus-visible': { outlineColor: '$sky12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky12',
      transition: 'all 0.3s ease',
    },
  },
  sky5: {
    backgroundColor: '$sky5',
    border: '1px solid $sky11',
    color: '$sky11',
    '&:active, &:focus-visible': { outlineColor: '$sky11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky11',
      transition: 'all 0.3s ease',
    },
  },
  sky6: {
    backgroundColor: '$sky6',
    border: '1px solid $sky11',
    color: '$sky11',
    '&:active, &:focus-visible': { outlineColor: '$sky11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky11',
      transition: 'all 0.3s ease',
    },
  },
  sky7: {
    backgroundColor: '$sky7',
    border: '1px solid $sky12',
    color: '$sky12',
    '&:active, &:focus-visible': { outlineColor: '$sky12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky12',
      transition: 'all 0.3s ease',
    },
  },
  sky8: {
    backgroundColor: '$sky8',
    border: '1px solid $sky12',
    color: '$sky12',
    '&:active, &:focus-visible': { outlineColor: '$sky12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky12',
      transition: 'all 0.3s ease',
    },
  },
  sky9: {
    backgroundColor: '$sky9',
    border: '1px solid $sky1',
    color: '$sky1',
    '&:active, &:focus-visible': { outlineColor: '$sky1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky1',
      transition: 'all 0.3s ease',
    },
  },
  sky10: {
    backgroundColor: '$sky10',
    border: '1px solid $sky1',
    color: '$sky1',
    '&:active, &:focus-visible': { outlineColor: '$sky1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky1',
      transition: 'all 0.3s ease',
    },
  },
  sky11: {
    backgroundColor: '$sky11',
    border: '1px solid $sky1',
    color: '$sky1',
    '&:active, &:focus-visible': { outlineColor: '$sky1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky1',
      transition: 'all 0.3s ease',
    },
  },
  sky12: {
    backgroundColor: '$sky12',
    border: '1px solid $sky1',
    color: '$sky1',
    '&:active, &:focus-visible': { outlineColor: '$sky1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$sky1',
      transition: 'all 0.3s ease',
    },
  },
  mint1: {
    backgroundColor: '$mint1',
    border: '1px solid $mint12',
    color: '$mint12',
    '&:active, &:focus-visible': { outlineColor: '$mint12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint12',
      transition: 'all 0.3s ease',
    },
  },
  mint2: {
    backgroundColor: '$mint2',
    border: '1px solid $mint12',
    color: '$mint12',
    '&:active, &:focus-visible': { outlineColor: '$mint12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint12',
      transition: 'all 0.3s ease',
    },
  },
  mint3: {
    backgroundColor: '$mint3',
    border: '1px solid $mint12',
    color: '$mint12',
    '&:active, &:focus-visible': { outlineColor: '$mint12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint12',
      transition: 'all 0.3s ease',
    },
  },
  mint4: {
    backgroundColor: '$mint4',
    border: '1px solid $mint12',
    color: '$mint12',
    '&:active, &:focus-visible': { outlineColor: '$mint12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint12',
      transition: 'all 0.3s ease',
    },
  },
  mint5: {
    backgroundColor: '$mint5',
    border: '1px solid $mint11',
    color: '$mint11',
    '&:active, &:focus-visible': { outlineColor: '$mint11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint11',
      transition: 'all 0.3s ease',
    },
  },
  mint6: {
    backgroundColor: '$mint6',
    border: '1px solid $mint11',
    color: '$mint11',
    '&:active, &:focus-visible': { outlineColor: '$mint11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint11',
      transition: 'all 0.3s ease',
    },
  },
  mint7: {
    backgroundColor: '$mint7',
    border: '1px solid $mint12',
    color: '$mint12',
    '&:active, &:focus-visible': { outlineColor: '$mint12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint12',
      transition: 'all 0.3s ease',
    },
  },
  mint8: {
    backgroundColor: '$mint8',
    border: '1px solid $mint12',
    color: '$mint12',
    '&:active, &:focus-visible': { outlineColor: '$mint12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint12',
      transition: 'all 0.3s ease',
    },
  },
  mint9: {
    backgroundColor: '$mint9',
    border: '1px solid $mint1',
    color: '$mint1',
    '&:active, &:focus-visible': { outlineColor: '$mint1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint1',
      transition: 'all 0.3s ease',
    },
  },
  mint10: {
    backgroundColor: '$mint10',
    border: '1px solid $mint1',
    color: '$mint1',
    '&:active, &:focus-visible': { outlineColor: '$mint1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint1',
      transition: 'all 0.3s ease',
    },
  },
  mint11: {
    backgroundColor: '$mint11',
    border: '1px solid $mint1',
    color: '$mint1',
    '&:active, &:focus-visible': { outlineColor: '$mint1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint1',
      transition: 'all 0.3s ease',
    },
  },
  mint12: {
    backgroundColor: '$mint12',
    border: '1px solid $mint1',
    color: '$mint1',
    '&:active, &:focus-visible': { outlineColor: '$mint1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mint1',
      transition: 'all 0.3s ease',
    },
  },
  lime1: {
    backgroundColor: '$lime1',
    border: '1px solid $lime12',
    color: '$lime12',
    '&:active, &:focus-visible': { outlineColor: '$lime12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime12',
      transition: 'all 0.3s ease',
    },
  },
  lime2: {
    backgroundColor: '$lime2',
    border: '1px solid $lime12',
    color: '$lime12',
    '&:active, &:focus-visible': { outlineColor: '$lime12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime12',
      transition: 'all 0.3s ease',
    },
  },
  lime3: {
    backgroundColor: '$lime3',
    border: '1px solid $lime12',
    color: '$lime12',
    '&:active, &:focus-visible': { outlineColor: '$lime12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime12',
      transition: 'all 0.3s ease',
    },
  },
  lime4: {
    backgroundColor: '$lime4',
    border: '1px solid $lime12',
    color: '$lime12',
    '&:active, &:focus-visible': { outlineColor: '$lime12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime12',
      transition: 'all 0.3s ease',
    },
  },
  lime5: {
    backgroundColor: '$lime5',
    border: '1px solid $lime11',
    color: '$lime11',
    '&:active, &:focus-visible': { outlineColor: '$lime11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime11',
      transition: 'all 0.3s ease',
    },
  },
  lime6: {
    backgroundColor: '$lime6',
    border: '1px solid $lime11',
    color: '$lime11',
    '&:active, &:focus-visible': { outlineColor: '$lime11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime11',
      transition: 'all 0.3s ease',
    },
  },
  lime7: {
    backgroundColor: '$lime7',
    border: '1px solid $lime12',
    color: '$lime12',
    '&:active, &:focus-visible': { outlineColor: '$lime12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime12',
      transition: 'all 0.3s ease',
    },
  },
  lime8: {
    backgroundColor: '$lime8',
    border: '1px solid $lime12',
    color: '$lime12',
    '&:active, &:focus-visible': { outlineColor: '$lime12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime12',
      transition: 'all 0.3s ease',
    },
  },
  lime9: {
    backgroundColor: '$lime9',
    border: '1px solid $lime1',
    color: '$lime1',
    '&:active, &:focus-visible': { outlineColor: '$lime1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime1',
      transition: 'all 0.3s ease',
    },
  },
  lime10: {
    backgroundColor: '$lime10',
    border: '1px solid $lime1',
    color: '$lime1',
    '&:active, &:focus-visible': { outlineColor: '$lime1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime1',
      transition: 'all 0.3s ease',
    },
  },
  lime11: {
    backgroundColor: '$lime11',
    border: '1px solid $lime1',
    color: '$lime1',
    '&:active, &:focus-visible': { outlineColor: '$lime1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime1',
      transition: 'all 0.3s ease',
    },
  },
  lime12: {
    backgroundColor: '$lime12',
    border: '1px solid $lime1',
    color: '$lime1',
    '&:active, &:focus-visible': { outlineColor: '$lime1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$lime1',
      transition: 'all 0.3s ease',
    },
  },
  amber1: {
    backgroundColor: '$amber1',
    border: '1px solid $amber12',
    color: '$amber12',
    '&:active, &:focus-visible': { outlineColor: '$amber12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber12',
      transition: 'all 0.3s ease',
    },
  },
  amber2: {
    backgroundColor: '$amber2',
    border: '1px solid $amber12',
    color: '$amber12',
    '&:active, &:focus-visible': { outlineColor: '$amber12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber12',
      transition: 'all 0.3s ease',
    },
  },
  amber3: {
    backgroundColor: '$amber3',
    border: '1px solid $amber12',
    color: '$amber12',
    '&:active, &:focus-visible': { outlineColor: '$amber12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber12',
      transition: 'all 0.3s ease',
    },
  },
  amber4: {
    backgroundColor: '$amber4',
    border: '1px solid $amber12',
    color: '$amber12',
    '&:active, &:focus-visible': { outlineColor: '$amber12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber12',
      transition: 'all 0.3s ease',
    },
  },
  amber5: {
    backgroundColor: '$amber5',
    border: '1px solid $amber11',
    color: '$amber11',
    '&:active, &:focus-visible': { outlineColor: '$amber11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber11',
      transition: 'all 0.3s ease',
    },
  },
  amber6: {
    backgroundColor: '$amber6',
    border: '1px solid $amber11',
    color: '$amber11',
    '&:active, &:focus-visible': { outlineColor: '$amber11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber11',
      transition: 'all 0.3s ease',
    },
  },
  amber7: {
    backgroundColor: '$amber7',
    border: '1px solid $amber12',
    color: '$amber12',
    '&:active, &:focus-visible': { outlineColor: '$amber12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber12',
      transition: 'all 0.3s ease',
    },
  },
  amber8: {
    backgroundColor: '$amber8',
    border: '1px solid $amber12',
    color: '$amber12',
    '&:active, &:focus-visible': { outlineColor: '$amber12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber12',
      transition: 'all 0.3s ease',
    },
  },
  amber9: {
    backgroundColor: '$amber9',
    border: '1px solid $amber1',
    color: '$amber1',
    '&:active, &:focus-visible': { outlineColor: '$amber1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber1',
      transition: 'all 0.3s ease',
    },
  },
  amber10: {
    backgroundColor: '$amber10',
    border: '1px solid $amber1',
    color: '$amber1',
    '&:active, &:focus-visible': { outlineColor: '$amber1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber1',
      transition: 'all 0.3s ease',
    },
  },
  amber11: {
    backgroundColor: '$amber11',
    border: '1px solid $amber1',
    color: '$amber1',
    '&:active, &:focus-visible': { outlineColor: '$amber1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber1',
      transition: 'all 0.3s ease',
    },
  },
  amber12: {
    backgroundColor: '$amber12',
    border: '1px solid $amber1',
    color: '$amber1',
    '&:active, &:focus-visible': { outlineColor: '$amber1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$amber1',
      transition: 'all 0.3s ease',
    },
  },
  gold1: {
    backgroundColor: '$gold1',
    border: '1px solid $gold12',
    color: '$gold12',
    '&:active, &:focus-visible': { outlineColor: '$gold12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold12',
      transition: 'all 0.3s ease',
    },
  },
  gold2: {
    backgroundColor: '$gold2',
    border: '1px solid $gold12',
    color: '$gold12',
    '&:active, &:focus-visible': { outlineColor: '$gold12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold12',
      transition: 'all 0.3s ease',
    },
  },
  gold3: {
    backgroundColor: '$gold3',
    border: '1px solid $gold12',
    color: '$gold12',
    '&:active, &:focus-visible': { outlineColor: '$gold12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold12',
      transition: 'all 0.3s ease',
    },
  },
  gold4: {
    backgroundColor: '$gold4',
    border: '1px solid $gold12',
    color: '$gold12',
    '&:active, &:focus-visible': { outlineColor: '$gold12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold12',
      transition: 'all 0.3s ease',
    },
  },
  gold5: {
    backgroundColor: '$gold5',
    border: '1px solid $gold11',
    color: '$gold11',
    '&:active, &:focus-visible': { outlineColor: '$gold11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold11',
      transition: 'all 0.3s ease',
    },
  },
  gold6: {
    backgroundColor: '$gold6',
    border: '1px solid $gold11',
    color: '$gold11',
    '&:active, &:focus-visible': { outlineColor: '$gold11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold11',
      transition: 'all 0.3s ease',
    },
  },
  gold7: {
    backgroundColor: '$gold7',
    border: '1px solid $gold12',
    color: '$gold12',
    '&:active, &:focus-visible': { outlineColor: '$gold12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold12',
      transition: 'all 0.3s ease',
    },
  },
  gold8: {
    backgroundColor: '$gold8',
    border: '1px solid $gold12',
    color: '$gold12',
    '&:active, &:focus-visible': { outlineColor: '$gold12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold12',
      transition: 'all 0.3s ease',
    },
  },
  gold9: {
    backgroundColor: '$gold9',
    border: '1px solid $gold1',
    color: '$gold1',
    '&:active, &:focus-visible': { outlineColor: '$gold1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold1',
      transition: 'all 0.3s ease',
    },
  },
  gold10: {
    backgroundColor: '$gold10',
    border: '1px solid $gold1',
    color: '$gold1',
    '&:active, &:focus-visible': { outlineColor: '$gold1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold1',
      transition: 'all 0.3s ease',
    },
  },
  gold11: {
    backgroundColor: '$gold11',
    border: '1px solid $gold1',
    color: '$gold1',
    '&:active, &:focus-visible': { outlineColor: '$gold1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold1',
      transition: 'all 0.3s ease',
    },
  },
  gold12: {
    backgroundColor: '$gold12',
    border: '1px solid $gold1',
    color: '$gold1',
    '&:active, &:focus-visible': { outlineColor: '$gold1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$gold1',
      transition: 'all 0.3s ease',
    },
  },
  bronze1: {
    backgroundColor: '$bronze1',
    border: '1px solid $bronze12',
    color: '$bronze12',
    '&:active, &:focus-visible': { outlineColor: '$bronze12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze12',
      transition: 'all 0.3s ease',
    },
  },
  bronze2: {
    backgroundColor: '$bronze2',
    border: '1px solid $bronze12',
    color: '$bronze12',
    '&:active, &:focus-visible': { outlineColor: '$bronze12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze12',
      transition: 'all 0.3s ease',
    },
  },
  bronze3: {
    backgroundColor: '$bronze3',
    border: '1px solid $bronze12',
    color: '$bronze12',
    '&:active, &:focus-visible': { outlineColor: '$bronze12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze12',
      transition: 'all 0.3s ease',
    },
  },
  bronze4: {
    backgroundColor: '$bronze4',
    border: '1px solid $bronze12',
    color: '$bronze12',
    '&:active, &:focus-visible': { outlineColor: '$bronze12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze12',
      transition: 'all 0.3s ease',
    },
  },
  bronze5: {
    backgroundColor: '$bronze5',
    border: '1px solid $bronze11',
    color: '$bronze11',
    '&:active, &:focus-visible': { outlineColor: '$bronze11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze11',
      transition: 'all 0.3s ease',
    },
  },
  bronze6: {
    backgroundColor: '$bronze6',
    border: '1px solid $bronze11',
    color: '$bronze11',
    '&:active, &:focus-visible': { outlineColor: '$bronze11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze11',
      transition: 'all 0.3s ease',
    },
  },
  bronze7: {
    backgroundColor: '$bronze7',
    border: '1px solid $bronze12',
    color: '$bronze12',
    '&:active, &:focus-visible': { outlineColor: '$bronze12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze12',
      transition: 'all 0.3s ease',
    },
  },
  bronze8: {
    backgroundColor: '$bronze8',
    border: '1px solid $bronze12',
    color: '$bronze12',
    '&:active, &:focus-visible': { outlineColor: '$bronze12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze12',
      transition: 'all 0.3s ease',
    },
  },
  bronze9: {
    backgroundColor: '$bronze9',
    border: '1px solid $bronze1',
    color: '$bronze1',
    '&:active, &:focus-visible': { outlineColor: '$bronze1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze1',
      transition: 'all 0.3s ease',
    },
  },
  bronze10: {
    backgroundColor: '$bronze10',
    border: '1px solid $bronze1',
    color: '$bronze1',
    '&:active, &:focus-visible': { outlineColor: '$bronze1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze1',
      transition: 'all 0.3s ease',
    },
  },
  bronze11: {
    backgroundColor: '$bronze11',
    border: '1px solid $bronze1',
    color: '$bronze1',
    '&:active, &:focus-visible': { outlineColor: '$bronze1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze1',
      transition: 'all 0.3s ease',
    },
  },
  bronze12: {
    backgroundColor: '$bronze12',
    border: '1px solid $bronze1',
    color: '$bronze1',
    '&:active, &:focus-visible': { outlineColor: '$bronze1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$bronze1',
      transition: 'all 0.3s ease',
    },
  },
  mauve1: {
    backgroundColor: '$mauve1',
    border: '1px solid $mauve12',
    color: '$mauve12',
    '&:active, &:focus-visible': { outlineColor: '$mauve12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve12',
      transition: 'all 0.3s ease',
    },
  },
  mauve2: {
    backgroundColor: '$mauve2',
    border: '1px solid $mauve12',
    color: '$mauve12',
    '&:active, &:focus-visible': { outlineColor: '$mauve12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve12',
      transition: 'all 0.3s ease',
    },
  },
  mauve3: {
    backgroundColor: '$mauve3',
    border: '1px solid $mauve12',
    color: '$mauve12',
    '&:active, &:focus-visible': { outlineColor: '$mauve12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve12',
      transition: 'all 0.3s ease',
    },
  },
  mauve4: {
    backgroundColor: '$mauve4',
    border: '1px solid $mauve12',
    color: '$mauve12',
    '&:active, &:focus-visible': { outlineColor: '$mauve12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve12',
      transition: 'all 0.3s ease',
    },
  },
  mauve5: {
    backgroundColor: '$mauve5',
    border: '1px solid $mauve11',
    color: '$mauve11',
    '&:active, &:focus-visible': { outlineColor: '$mauve11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve11',
      transition: 'all 0.3s ease',
    },
  },
  mauve6: {
    backgroundColor: '$mauve6',
    border: '1px solid $mauve11',
    color: '$mauve11',
    '&:active, &:focus-visible': { outlineColor: '$mauve11' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve11',
      transition: 'all 0.3s ease',
    },
  },
  mauve7: {
    backgroundColor: '$mauve7',
    border: '1px solid $mauve12',
    color: '$mauve12',
    '&:active, &:focus-visible': { outlineColor: '$mauve12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve12',
      transition: 'all 0.3s ease',
    },
  },
  mauve8: {
    backgroundColor: '$mauve8',
    border: '1px solid $mauve12',
    color: '$mauve12',
    '&:active, &:focus-visible': { outlineColor: '$mauve12' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve12',
      transition: 'all 0.3s ease',
    },
  },
  mauve9: {
    backgroundColor: '$mauve9',
    border: '1px solid $mauve1',
    color: '$mauve1',
    '&:active, &:focus-visible': { outlineColor: '$mauve1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve1',
      transition: 'all 0.3s ease',
    },
  },
  mauve10: {
    backgroundColor: '$mauve10',
    border: '1px solid $mauve1',
    color: '$mauve1',
    '&:active, &:focus-visible': { outlineColor: '$mauve1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve1',
      transition: 'all 0.3s ease',
    },
  },
  mauve11: {
    backgroundColor: '$mauve11',
    border: '1px solid $mauve1',
    color: '$mauve1',
    '&:active, &:focus-visible': { outlineColor: '$mauve1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve1',
      transition: 'all 0.3s ease',
    },
  },
  mauve12: {
    backgroundColor: '$mauve12',
    border: '1px solid $mauve1',
    color: '$mauve1',
    '&:active, &:focus-visible': { outlineColor: '$mauve1' },
    '&:hover, &:focus': {
      cursor: 'pointer',
      transform: 'translateY(-2px)',
      boxShadow: '$mauve1',
      transition: 'all 0.3s ease',
    },
  },
} as Record<
  COLORS_WITHOUT_KINDS,
  {
    '&:active, &:focus-visible': { outlineColor: string };
    '&:hover, &:focus': {
      transform: string;
      boxShadow: string;
      cursor: string;
      transition: string;
    };
  }
>;
