import {
  gray,
  blue,
  red,
  green,
  purple,
  yellow,
  orange,
  grayDark,
  blueDark,
  redDark,
  greenDark,
  purpleDark,
  yellowDark,
  orangeDark,
} from '@radix-ui/colors';

export const colors = {
  default: {
    ...purple,
    ...green,
    ...blue,
    ...red,
    ...yellow,
    ...orange,
    ...gray,
    purple: '#6c0392',
    green: '#38f689',
    blue: '#00bfff',
    red: '#ff6347',
    yellow: '#ffd700',
    orange: '#f4b350',
    grey: '#d5d5d5',
    black: '#111827',
    white: '#FEFEFE',
  },
  dark: {
    ...purpleDark,
    ...greenDark,
    ...blueDark,
    ...redDark,
    ...yellowDark,
    ...orangeDark,
    ...grayDark,
    purple: '#4b0266',
    green: '#219352',
    blue: '#007299',
    red: '#993b2a',
    yellow: '#998100',
    orange: '#996300',
    grey: '#7f7f7f',
    black: '#e4e4e4',
    white: '#0a0e17',
  },
};
